### ISSUE TITLE
Create a nice inviting image for the event page

### ISSUE THREAD

**Issue by poppyseedDev** [poppyseedDev/her-dao-polkadot-meetup#1]
Should follow the Polkadot guidelines for creating events.

Where can I find these guidelines?

**Comment by JustLuuuu** [comment]
https://web3foundation.notion.site/Community-Events-Bounty-3dc41e32c4f64dc5bee5ad60c3a22432

**Comment by JustLuuuu** [comment]
Bradning guidelines: https://file.notion.so/f/s/c59e63e6-6347-449b-8912-cbf84f0a2d7f/Polkadot_Events_Branding_Guidelines.pdf?id=d54534d1-f493-4bbd-8d22-c4fc69087728&table=block&spaceId=bdd0695f-fc31-4983-a79e-556261255932&expirationTimestamp=1692871200000&signature=9EKxGBnBVq0n9bLr_ghylQ1otE7mmisYT4L8biUMNmE&downloadName=Polkadot+Events+Branding+Guidelines.pdf

**Comment by JustLuuuu** [comment]
Done by aurora ❤️
