### ISSUE TITLE
Prepare Program

### ISSUE THREAD

**Issue by JustLuuuu** [poppyseedDev/her-dao-polkadot-meetup#10]
Just to have the plan how the event will go:

- welcome talk - just a short welcome talk - 2-3 minutes about the idea and motivation behind the event
- introduction - organisers should introduce themselves
- introduction circle (it will be cool if we can encourage all girls to shortly introduce themselves) 
- open chat & breakfast

**Comment by poppyseedDev** [comment]
I think what you mentioned is a good enough program, we don't even need to make it so structured, but maybe it would be nice to put this into the event description 😊

**Comment by poppyseedDev** [comment]
Updated program on event page:

https://lu.ma/dzuqx5nw

​🥐☕ Event Flow:
​Welcome Talk (2-3 mins): A quick dive into the event's motivation and purpose.

​Introduction: Time for the organisers, Aurora and Luuu, to shine a light on their journey.

​Introduction Circle: A moment for all our incredible attendees. We'd love to hear everyone's story, so let's encourage a short introduction from each attendee.

​Open Chat & Breakfast: Mingle, chat, and enjoy a delicious breakfast. It's all about connection!
