### ISSUE TITLE
Budget Calculation

### ISSUE THREAD

**Issue by JustLuuuu** [poppyseedDev/her-dao-polkadot-meetup#2]
## What
Create a table we can include in the calculations for the budget for our proposal.

## Include
- venue
- food/drinks
- paop (maybe)

**Comment by poppyseedDev** [comment]
So current calculations are 20 euros for the breakfast per person 25 people, are there any other expenses we are expecting?

So now we are at 700 euro

https://github.com/poppyseedDev/her-dao-polkadot-meetup/commit/21b189d7edc3bf6f660b73bd952fa408d641a77a

**Comment by JustLuuuu** [comment]
I would say no, I'm not sure about that POAP if we need it, we can create something on our own. Creating a new POAP would cost 100+ eur

**Comment by poppyseedDev** [comment]
All the budget calculations are here:

https://github.com/poppyseedDev/her-dao-polkadot-meetup/blob/main/budget.md
