### ISSUE TITLE
Create Treasury Proposal

### ISSUE THREAD

**Issue by JustLuuuu** [poppyseedDev/her-dao-polkadot-meetup#3]
## What
Create proposal to get funding

## Tasks
- research how to make proposal
- create proposal
- submit it

**Comment by JustLuuuu** [comment]
How to prepare proposal: https://web3foundation.notion.site/Community-Events-Bounty-3dc41e32c4f64dc5bee5ad60c3a22432

**Comment by poppyseedDev** [comment]
The treasury proposal was submitted. Let's see how the voting process goes.
