### ISSUE TITLE
Secure Venue + Catering

### ISSUE THREAD

**Issue by JustLuuuu** [poppyseedDev/her-dao-polkadot-meetup#9]
## What
- Find a suitable venue: Do research
- Confirm venue 
- Get an invoice for food+ and drinks for 20 people. (we will need this for proposal)

## Venue should
- not be a very busy place - or at least have separate spaces for us so we are not mixed with other people.

**Comment by poppyseedDev** [comment]
Sub0 location: https://goo.gl/maps/EuQ2utrEFD252Puu9

**Comment by poppyseedDev** [comment]
I contacted:
The Food for Real Alcântara - https://goo.gl/maps/uRwAG8h1roRiBnJFA
Bloom: https://goo.gl/maps/YrwvdnGC9G7EDQAX7
Heim Cafe: https://goo.gl/maps/hmoh6EQAXBWntjZP8
the mill: https://goo.gl/maps/9oBixFEPmaCGoLdMA - response: we can't make a reservation


---

I  am using this email:


Subject: Breakfast Reservation Inquiry for September 20th, 9:30am - 11:30am



Hello [Breakfast Place Name],

I hope this message finds you well.

I'm reaching out to inquire about the possibility of reserving a space at your establishment for a breakfast gathering on the 20th of September from 9:30am to 11:30am. We are anticipating a group of 20 people.

Could you kindly provide an approximate cost per person for a sandwich and a drink during these hours? We're trying to budget in advance and would greatly appreciate an estimate.

Thank you in advance for your assistance. We've heard wonderful things about your place and are excited about the possibility of hosting our event with you.

Looking forward to your response.

Warm regards,

[Your Name]

**Comment by JustLuuuu** [comment]
[Go A Lisboa](https://goo.gl/maps/DRyi5KEEXb77yoFu5) - they have a lovely rooftop!! How about this space? Its possible to book it online! What day do we want to have our event?

**Comment by JustLuuuu** [comment]
> [Go A Lisboa](https://goo.gl/maps/DRyi5KEEXb77yoFu5) - they have a lovely rooftop!! How about this space? Its possible to book it online! What day do we want to have our event? I contacted them!

**Comment by poppyseedDev** [comment]
I remember there was an event here last year for the sub0. It's a lovely place.

The only thing that I am worried about is that they don't have a possibilty to reserve in the morning.

**Comment by poppyseedDev** [comment]
> 

20th 9:30 - 11:30 am

**Comment by poppyseedDev** [comment]
Contacted: 
Gin Lovers: https://goo.gl/maps/sNqGsimMC7y75tpf7
They said that there shouldn't be a problem with the reservation, they normally open at 12, however that we can negotiate with them and they can make a breakfast menu as well. However I think this will be one of the more pricey options

**Comment by poppyseedDev** [comment]
Venue secure: https://goo.gl/maps/NbeCJ48Y6cTpHWZg9

My comments: 
The food looks, nice, the guy is super kind, it's close to the venue
It's perfect!
maybe a bit small but it will be cosy
